### ISSUE TITLE
dotplot

### ISSUE THREAD

**Issue by duhuipeng** [rlorigro/simple-dotplot#1]
dear author
I ran my own individual data (only centromeric regions) based on the process example you provided, but this error appears below
![image](https://user-images.githubusercontent.com/58722433/149166699-f346dc73-f4cf-4b47-95a3-82c75968c293.png)
How do I need to solve the problem?
The second question, if I want to compare the results of centromeric regions of the same chromosome in different individuals, can I use this code to only modify query, and other parameters do not change (eg.: ./dotplot --ref D1/chr5CEN.fa --query C1/chr5CEN.fasta --min_length 1024 --output_dir /hl/simple/test --mask_diagonal )
Hope to get your answer

Best
HuipengDu

**Comment by rlorigro** [comment]
Hi HuipengDu,

This is because your output directory cannot be present already when you run the executable. When you choose a name for `--output_dir` it must be a new name that does not exist on the hard drive. This is to prevent overwriting previous runs.

For your second question, you are correct, you would simply change the query path to whichever sequence you are interested in. However, as I mentioned before, you may not overwrite an existing output directory so you would also need to make sure that is a new name.

**Comment by duhuipeng** [comment]
thanks

**Comment by rlorigro** [comment]
If this resolves your issue please let me know.

**Comment by duhuipeng** [comment]
Dear author
This is the result diagram that I drew out 
![image](https://user-images.githubusercontent.com/58722433/149280712-9d04526d-a7f0-4f31-896e-85982b7519e2.png)
I would like to consult on how this figure in the article is drawn,How does this background color be set, I also want to achieve the background color effect in the article, and where should I modify this parameter.(as follow)
![image](https://user-images.githubusercontent.com/58722433/149281552-a9fed9c0-852a-4f3a-a276-8121e31a2d78.png)
There is also a little problem:
It is this parameter- -min_length. What is it value generally set according to?(Is it the exact unit length of it HOR ? )

Hope to get your answer

Best
HuipengDu

**Comment by rlorigro** [comment]
Hi HuipengDu,

At the moment the dotplot executable is using the viridis colormap. So any time the max observed match length for a coordinate falls within a certain percent of the longest match, it may be blue. 

![image](https://user-images.githubusercontent.com/28764332/149688460-faf591a1-a787-44c9-9311-7e40e208d37b.png)


Here is a short explanation I wrote for the censat paper:

```
Dotplots were generated by computing an exhaustive search for exact matches between any 2 sequences, where matches are
>= 16bp. A 2D matrix then stores the length of the longest match within square bins that are 1/nth the length of the
longest sequence, where n is the number of pixels desired in the output image. The matrix is then normalized from 0-1
where 1.0 is the longest observed match, and log scaled. The values are interpreted as a color in the Viridis colormap
and rendered as an (n,n)px image.
```

The reason that the figure you showed looks blue is because it found many more matches, because the minimum match length was set to 16bp instead of 1024 as you have. 16bp will take much longer (about 5-10min) to run but you will get more information and the full matrix will be filled in.

Hope that helps. I could add an option to output the raw matrix so you can re-plot it in python using any colormap you want, if that would be helpful.

**Comment by duhuipeng** [comment]
Dear author

I understand the second question you said, but the first one still doesn't
I looked through the code inside the githup and I changed the range of parameter values for the color(as follow)
![image](https://user-images.githubusercontent.com/58722433/149705598-88db4df4-4852-4d4a-b968-7c68e63a0bc7.png)
But I have found that the color of the background has not changed(as follow)
![image](https://user-images.githubusercontent.com/58722433/149705705-40918cb6-008c-4620-993c-e12b8a0edde6.png)
I  guess that I misunderstand your advise

Hope to get your detailed guidance again
I'm really sorry for disturbing it again

Best
HuipengDu

**Comment by rlorigro** [comment]
Hi,

The code you shared is from a python script which does not have any effect on the C++ dotplot executable you ran to create your images.

My recommendation would be to try a much shorter match length and see how it looks, before you try anything else.

**Comment by duhuipeng** [comment]
dear author
this is the -min_length 16 result
![image](https://user-images.githubusercontent.com/58722433/149719191-4b60e103-107a-4591-8474-4d1e0b9751fe.png)
It hasn't changed much, or it can't get the effect I want in your picture
what should I do next?

Best
HuipengDu

**Comment by rlorigro** [comment]
Hi HuipengDu,

That doesn't look like the same comparison, but regardless, I understand that you are interested in customizing the color range, so I have added an additional output to the dotplot executable. You will need to fetch and pull the latest changes from the main branch and recompile your source code.

Now when you run the program a CSV file will be generated that contains all the raw data from the match-finding step. Then, you can run (and edit as you see fit) the python script I have added as `simple_dotplot/scripts/plot_csv.py`. Here is an example:

```
./build/dotplot --ref /home/ryan/data/censat2021/1.chm13.cenX.fasta --query /home/ryan/data/censat2021/1.chm13.cenX.fasta -l 1024 -o test_dotplot_csv

 python3 scripts/plot_csv.py -i /home/ryan/code/simple-dotplot/build/test_dotplot_csv/1.chm13.cenX_VS_chrX_57820107_60927026_dotplot.csv
 ```
 
 Now if you edit that script you can re-plot it with any colormap you like:
 
 ```
 pyplot.imshow(matrix, cmap=truncate_colormap(cm.get_cmap('jet', 256), minval=0, maxval=1.0))
 ```
![image](https://user-images.githubusercontent.com/28764332/150030017-d72ad9d7-1577-47f8-a9a7-b3eb77f9e1b2.png)

```
    pyplot.imshow(matrix, cmap=truncate_colormap(cm.get_cmap('gist_rainbow', 256), minval=0, maxval=1.0))
```
![image](https://user-images.githubusercontent.com/28764332/150030224-9359e860-2549-4a36-b886-8e5bd106b57b.png)


```
    pyplot.imshow(matrix, cmap=truncate_colormap(cm.get_cmap('gist_rainbow', 256), minval=0.07, maxval=0.8))
```
![image](https://user-images.githubusercontent.com/28764332/150030396-e98e8b17-04c6-4811-ba93-03bf629fe111.png)

```
    pyplot.imshow(matrix, cmap=truncate_colormap(cm.get_cmap('gnuplot2', 256), minval=0.0, maxval=1.0))
```
![image](https://user-images.githubusercontent.com/28764332/150030730-83d54430-c462-4975-94f0-4a4c81779678.png)

Let me know if this works for you. You may still want to play with different combinations of match length and colormap to get what you want.

**Comment by duhuipeng** [comment]
Dear author
Since I have been busy sorting out the experimental samples recently,I can not see your reply in time, I am really sorry for this.Just now I downloaded and compiled it again as you said,I had this problem at runtime(as follow)
![image](https://user-images.githubusercontent.com/58722433/150128773-abf33473-dd00-4072-92b5-7caa56d14972.png)
It prompted me that this fasta file was not found but actually this file exists(as follow)
![image](https://user-images.githubusercontent.com/58722433/150130808-decc279a-01d2-4e04-897e-fd32685148f2.png)
what should I do ?
Best
HuipengDu

**Comment by duhuipeng** [comment]
Dear author
Because I have been busy sorting out the experimental samples in these two days, I failed to see your reply in time,I really feel sorry for keeping you waiting for a long time.I just started downloading and compiling it as you suggested,My run-code is as follows,
 ./dotplot --ref /hl/DHP/simple/DRC/chr5CEN.fasta --query /hl/DHP/simple/DRC/chr5CEN.fasta -l 1024 -o test_dotplot_csv
python3 ../scripts/plot_csv.py -i /hl/DHP/DRC/simple-dotplot-main/build/test_dotplot_csv/chr5CEN_VS_DRC_chr5_dotplot.csv
I found that it had the problems as follow:
When I run the first step, he produces the ppm picture for this file,I was running the second line of code that you prompted and found that I was not handling this picture at all.
My color modification is as you provided, as shown below
![image](https://user-images.githubusercontent.com/58722433/150138032-833deb69-61fe-414c-ae53-5e9e0a4224c1.png)
the picture as follow :
![image](https://user-images.githubusercontent.com/58722433/150138849-6d114dae-6af0-4a66-8623-69957fb9afc5.png)

But the color background of this figure  not changed ,The graph is the same color background as the graph generated by running the first code you provide.When I removed the result of the ppm generated in the first step,and  in running the second line of code I found that there was no error reported and there was do not ppm file generated .
I guess that is why the color background hasn't changed.
what should I do ?

Best
HuipengDu

**Comment by rlorigro** [comment]
When you run plot_csv (as it is currently written) it does not produce a new file, it only uses the "show()" command to display the window interactively. You are running it on a server, which probably prevents the window from appearing. Can you download the CSV and the python script and run it locally?

In general, you do not need a server to run this program, because it is fairly memory-efficient.

**Comment by duhuipeng** [comment]
Dear author
Following your advice, the pictures ran out ,as follow:
![image](https://user-images.githubusercontent.com/58722433/150293234-de421324-cbe3-467a-8a2e-e1f350aaf167.png)
But I modified the color as follows, why  is green rather than the background color is red you give:
![image](https://user-images.githubusercontent.com/58722433/150293458-903d21b1-ad9b-4a33-af65-1b6cbe7af0d0.png)

Best
HuipengDu

**Comment by rlorigro** [comment]
Because it's truncated

**Comment by duhuipeng** [comment]
thanks,I got

**Comment by rlorigro** [comment]
OK, if this resolves your issue, I will go ahead and close it. Feel free to open another issue if you run into more problems.
